apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: agreed-wolverine-python 
  janus-idp.io/tekton: agreed-wolverine-python
  backstage.io/kubernetes-id: agreed-wolverine-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: agreed-wolverine-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  